AllCops:
  NewCops: enable

Metrics/AbcSize:
  Max: 28

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 25
  Exclude:
    - spec/**/*.rb

Metrics/MethodLength:
  Max: 10
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call
