services:
  tg-currency-bot:
    container_name: tg-currency-bot
    image: tg-bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db:/app/db
    environment:
      - TZ
      - TELEGRAM_TOKEN
      - TELEGRAM_CHAT_ID
      - MONO_API_TOKEN
      - TEST_RUN
      - APP_ENV=production
